BadmintonReservationWebApp/Controllers/CourtController.cs
using Microsoft.AspNetCore.Mvc;
using BadmintonReservationData;
using Newtonsoft.Json;
using BadmintonReservationData.DTO;
using System.Text;
using BadmintonReservationData.DTOs;
using BadmintonReservationWebApp.Models;

namespace BadmintonReservationWebApp.Controllers
{
    public class CourtController : Controller
    {
        private const string URL = "https://localhost:7257/";

        // GET: Court
        public async Task<IActionResult> Index()
        {
            
            return View();
        }

        [HttpGet]
        public async Task<PageableResponseDTO<Court>> GetAll(CourtSearchCondition condition)
        {
            try
            {
                var queryParameter = CourtController.ToQueryString(condition);
                var result = new PageableResponseDTO<Court>();
                string baseUrl = URL + "api/Court/GetAll" + queryParameter;
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(baseUrl))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var content = await response.Content.ReadAsStringAsync();
                            result = JsonConvert.DeserializeObject<PageableResponseDTO<Court>>(content);
                        }
                    }
                }

                return result;
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("add", new CreateCourtDTO());
        }

        [HttpPost]
        public async Task<Court> Create([FromBody] CreateCourtDTO createCourtDTO)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    var json = JsonConvert.SerializeObject(createCourtDTO);
                    var content = new StringContent(json, Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync(URL + "api/Court", content))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var responseContent = await response.Content.ReadAsStringAsync();
                            var court = JsonConvert.DeserializeObject<Court>(responseContent);
                            return court;
                        }
                        else
                        {
                            throw new Exception(
                                $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Internal server error: {ex.Message}");
            }
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                UpdateCourtDTO result = null;
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{URL}api/Court/GetById/{id}"))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var content = await response.Content.ReadAsStringAsync();
                            var courtResponse = JsonConvert.DeserializeObject<Court>(content);
                            result = new UpdateCourtDTO()
                            {
                                Id = courtResponse.Id,
                                Name = courtResponse.Name,
                                Status = courtResponse.Status,
                                OpeningHours = courtResponse.OpeningHours,
                                CloseHours = courtResponse.CloseHours,
                                SurfaceType = courtResponse.SurfaceType,
                                CourtType = courtResponse.CourtType,
                                Amentities =courtResponse.Amentities,
                                Capacity = courtResponse.Capacity
                             
                            };
                        }
                    }
                }

                return PartialView("edit", result);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPut]
        public async Task<UpdateCourtDTO> Update([FromBody] UpdateCourtDTO udpateCourt)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    var json = JsonConvert.SerializeObject(udpateCourt);
                    var content = new StringContent(json, Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PutAsync($"{URL}api/Court/{udpateCourt.Id}", content))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var responseContent = await response.Content.ReadAsStringAsync();
                            var updatedFrame = JsonConvert.DeserializeObject<UpdateCourtDTO>(responseContent);
                            return updatedFrame;
                        }
                        else
                        {
                            throw new Exception(
                                $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Internal server error: {ex.Message}");
            }
        }


        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    HttpResponseMessage response = await httpClient.DeleteAsync($"{URL}api/Court/{id}");
                    if (response.IsSuccessStatusCode)
                    {
                        return NoContent();
                    }
                    else
                    {
                        return StatusCode((int)response.StatusCode);
                    }
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"An error occurred: {ex.Message}");
            }
        }


        [HttpGet]
        public async Task<IActionResult> Report(int id)
        {
            try
            {
                CourtReport result = null;
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{URL}api/Court/GetById/{id}"))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var content = await response.Content.ReadAsStringAsync();
                            var courtResponse = JsonConvert.DeserializeObject<Court>(content);
                            result = new CourtReport()
                            {
                                Id = courtResponse.Id,
                                Name = courtResponse.Name,
                                Status = courtResponse.Status,
                                OpeningHours = courtResponse.OpeningHours,
                                CloseHours = courtResponse.CloseHours,
                                SurfaceType = courtResponse.SurfaceType,
                                CourtType = courtResponse.CourtType,
                                Amentities = courtResponse.Amentities,
                                Capacity = courtResponse.Capacity,
                                CreatedDate = courtResponse.CreatedDate,
                                UpdatedDate = courtResponse.UpdatedDate,
                                TotalBooking = courtResponse.TotalBooking
                            };
                        }
                    }

                    using (var response = await httpClient.GetAsync($"{URL}api/Frame/Court/{id}"))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var content = await response.Content.ReadAsStringAsync();
                            var frameResponse = JsonConvert.DeserializeObject<List<Frame>>(content);
                            if(frameResponse != null && frameResponse.Count > 0)
                            {
                                result.Frames = frameResponse;
                            }
                        }
                    }
                }

                return View("report", result);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


        public static string ToQueryString(object obj)
        {
            var properties = from p in obj.GetType().GetProperties()
                             where p.GetValue(obj, null) != null
                             select p.Name + "=" + Uri.EscapeDataString(p.GetValue(obj, null).ToString());

            return "?" + string.Join("&", properties.ToArray());
        }


    }
}

BadmintonReservationWebApp/Views/Frame/Add.cshtml
@model BadmintonReservationData.DTOs.CreateFrameRequestDTO
@{
    string ConvertToTimeString(int time)
    {
        int hours = time / 100;
        int minutes = time % 100;
        return $"{hours:D2}:{minutes:D2}";
    }
}
<div class="form-group row">
    <div class="col-md-6">
        <label for="Label">Label</label>
        @Html.EditorFor(model => model.Label, new { htmlAttributes = new { @class = "form-control", type= "text"} })
        @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="Note">Note</label>
        @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control", type= "text"} })
        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="TimeFrom">Time From</label>
        <input type="time" id="TimeFrom" name="TimeFrom" class="form-control" value="@ConvertToTimeString(Model.TimeFrom)" />
        @Html.ValidationMessageFor(model => model.TimeFrom, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="TimeTo">Time To</label>
        <input type="time" id="TimeTo" name="TimeTo" class="form-control" value="@ConvertToTimeString(Model.TimeTo)" />
        @Html.ValidationMessageFor(model => model.TimeTo, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Price</label>
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="1">Status</label>
        @Html.DropDownListFor(model => model.Status, new SelectList(new[]
        {
            new { Value = 1, Text = "Active" },
            new { Value = 2, Text = "Inactive" },
        }, "Value", "Text"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Court</label>
        <select id="CourtId" class="form-control"></select>
        @Html.ValidationMessageFor(model => model.CourtId, "", new { @class = "text-danger" })
    </div>
</div>
<script>
    $(document).ready(function() {
        getAllCourt();
    });
    function getAllCourt() {
        $.ajax({
            url: '@Url.Action("GetAll", "Court")',
                type: "GET",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                data: {
                    pageIndex: 1,
                    pageSize: 1000
                },
                success: function (result) {
                    // Clear previous options
                    $('#CourtId').empty();
                    // Add each court as an option to the dropdown list
                    $.each(result.list, function(key, item) {
                        $('#CourtId').append($('<option>', {
                            value: item.id,
                            text: item.name + ' | ' + item.amentities
                        }));
                    });
                },
                error: function (xhr, error) {
                    alert(xhr.statusText);
                    alert(`Something went wrong!`);
                }
        });
    }



</script>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

BadmintonReservationWebApp/Views/Frame/Edit.cshtml
@model BadmintonReservationData.DTOs.UpdateFrameRequestDTO

<div class="form-group row">
    <div class="col-md-6">
        <label for="Label">Label</label>
        @Html.EditorFor(model => model.Label, new { htmlAttributes = new { @class = "form-control", type= "text"} })
        @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="Note">Note</label>
        @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control", type= "text"} })
        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Time From</label>
        @Html.EditorFor(model => model.TimeFrom, new { htmlAttributes = new { @class = "form-control", @type = "time" } })
        @Html.ValidationMessageFor(model => model.TimeFrom, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="1">Time To</label>
        @Html.EditorFor(model => model.TimeTo, new { htmlAttributes = new { @class = "form-control", @type = "time" } })
        @Html.ValidationMessageFor(model => model.TimeTo, "", new { @class = "text-danger" })
    </div>
    @Html.EditorFor(model => model.OldTimeFrom, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
    @Html.EditorFor(model => model.OldTimeTo, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
    @Html.EditorFor(model => model.OldCourtId, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Price</label>
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="1">Status</label>
        @Html.DropDownListFor(model => model.Status, new SelectList(new[]
        {
            new { Value = 1, Text = "Active" },
            new { Value = 2, Text = "Inactive" },
        }, "Value", "Text"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Court</label>
        <select id="CourtId" class="form-control"></select>
        @Html.ValidationMessageFor(model => model.CourtId, "", new { @class = "text-danger" })
    </div>
</div>
<script>
    $(document).ready(function() {
        getAllCourt(@Model.CourtId);
    });

    function getAllCourt(selectedCourtId) {
        $.ajax({
            url: '@Url.Action("GetAll", "Court")',
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            data: {
                pageIndex: 1,
                pageSize: 1000
            },
            success: function (result) {
                // Clear previous options
                $('#CourtId').empty();
                // Add each court as an option to the dropdown list
                $.each(result.list, function(key, item) {
                    $('#CourtId').append($('<option>', {
                        value: item.id,
                        text: item.name + ' | ' + item.amentities,
                        selected: item.id === selectedCourtId
                    }));
                });
            },
            error: function (xhr, error) {
                alert(xhr.statusText);
                alert('Something went wrong!');
            }
        });
    }
</script>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

BadmintonReservationWebApp/Views/Frame/Report.cshtml
@model BadmintonReservationData.Frame
@{
    ViewData["Title"] = "Frame Report #" + Model.Id;
    var statusMap = new Dictionary<int, string>
    {
        { 1, "Active" },
        { 2, "InActive" }
    };

    var statusBadgeMap = new Dictionary<int, string>
    {
        { 1, "bg-success" },//Active
        { 2, "bg-danger" } //InActive
    };

    string ConvertIntTime(int hhmm)
    {
        string timeString = hhmm.ToString().PadLeft(4, '0');
        string hours = timeString.Substring(0, 2);
        string minutes = timeString.Substring(2, 2);
        return $"{hours}:{minutes}";
    }

    string FormatDate(DateTime date)
    {
        return date.ToString("dddd, dd-MM-yyyy");
    }

    string FormatDateTime(DateTime date)
    {
        return date.ToString("dddd, dd-MM-yyyy HH:mm");
    }

    string FormatPriceVND(double price)
    {
        return price.ToString("N0") + " VND";
    }
}
<style>
    body {
        font-family: Arial, sans-serif;
    }

    .header-text {
        color: #0188A6;
        font-weight: 600;
    }
    .header-line {
        background-color: #00a6BD4E;
        padding: 20px;
        color: white;
        font-size: 24px;
    }

    .header-text {
        display: flex;
        align-items: center;
    }

    .header-text .badge {
        margin-left: 10px;
        }

    .details, .details dt, .details dd {
        font-size: 18px;
    }

        .details dt {
            font-weight: bold;
        }

        .details dd {
            margin: 0 0 10px;
        }

    .table {
        margin-top: 20px;
    }

        .table th, .table td {
            text-align: center;
            vertical-align: middle;
        }
</style>
<div class="container">
    <h3 class="header-text">Frame Report #@Model.Id <span class="badge @statusBadgeMap[@Model.Status]" style="font-size: 14px;">@statusMap[@Model.Status]</span> </h3>
    <div class="header-line">
    </div>

    <dl class="row details mt-3">
        <div class="col-md-6 row">
            <dt class="col-sm-4">Label:</dt>
            <dd class="col-sm-8">@Model.Label</dd>

            <dt class="col-sm-4">Time From:</dt>
            <dd class="col-sm-8">@ConvertIntTime(@Model.TimeFrom)</dd>

            <dt class="col-sm-4">Time To:</dt>
            <dd class="col-sm-8">@ConvertIntTime(@Model.TimeTo)</dd>

            <dt class="col-sm-4">Price:</dt>
            <dd class="col-sm-8">@FormatPriceVND(@Model.Price)</dd>
        </div>
        <div class="col-md-6 row">
            <dt class="col-sm-4">Note:</dt>
            <dd class="col-sm-8">@Model.Note</dd>

            <dt class="col-sm-4">Court Name:</dt>
            <dd class="col-sm-8">@Model.Court.Name</dd>

            <dt class="col-sm-4">Frame Created:</dt>
            <dd class="col-sm-8">@FormatDateTime(@Model.CreatedDate)</dd>

            <dt class="col-sm-4">Last Updated At:</dt>
            <dd class="col-sm-8">@FormatDateTime(@Model.UpdatedDate)</dd>
        </div>
    </dl>
</div>