BadmintonReservationWebApp/Controllers/CustomFrameController.cs
using BadmintonReservationData.DTOs;
using BadmintonReservationData;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace BadmintonReservationWebApp.Controllers
{
    public class CustomFrameController : Controller
    {
        private readonly string API_URL_ENDPOINT = "https://localhost:7257/api/CustomFrame";

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("Add", new CreateCustomFrameRequestDTO());
        }

        [HttpGet]
        public async Task<List<CustomFrameDTO>> GetAll()
        {
            try
            {
                var result = new List<CustomFrameDTO>();
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(API_URL_ENDPOINT + "/GetAll"))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var content = await response.Content.ReadAsStringAsync();
                            result = JsonConvert.DeserializeObject<List<CustomFrameDTO>>(content);
                        }
                    }
                }

                return result;
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        public async Task<CustomFrameDTO> Create([FromBody] CreateCustomFrameRequestDTO createFrameRequestDto)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    var json = JsonConvert.SerializeObject(createFrameRequestDto);
                    var content = new StringContent(json, Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync(API_URL_ENDPOINT + "/Create", content))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var responseContent = await response.Content.ReadAsStringAsync();
                            var createdFrame = JsonConvert.DeserializeObject<CustomFrameDTO>(responseContent);
                            return createdFrame;
                        }
                        else
                        {
                            throw new Exception(
                                $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Internal server error: {ex.Message}");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                UpdateCustomFrameRequestDTO result = null;
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{API_URL_ENDPOINT}/GetById/{id}"))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var content = await response.Content.ReadAsStringAsync();
                            var frameResponse = JsonConvert.DeserializeObject<CustomFrame>(content);
                            result = new UpdateCustomFrameRequestDTO()
                            {
                                Id = frameResponse.Id,
                                FrameId = frameResponse.FrameId,
                                Price = frameResponse.Price,
                                SpecificDate = frameResponse.SpecificDate,
                                DateType = frameResponse.FixedDateTypeId,
                                Status = frameResponse.Status
                            };
                        }
                    }
                }

                return PartialView("edit", result);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPut]
        public async Task<Frame> Update([FromBody] UpdateCustomFrameRequestDTO updateCusFrameRequestDto)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    var json = JsonConvert.SerializeObject(updateCusFrameRequestDto);
                    var content = new StringContent(json, Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PutAsync($"{API_URL_ENDPOINT}/Update", content))
                    {
                        if (response.IsSuccessStatusCode)
                        {
                            var responseContent = await response.Content.ReadAsStringAsync();
                            var updatedFrame = JsonConvert.DeserializeObject<Frame>(responseContent);
                            return updatedFrame;
                        }
                        else
                        {
                            throw new Exception(
                                $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Internal server error: {ex.Message}");
            }
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    HttpResponseMessage response = await httpClient.DeleteAsync($"{API_URL_ENDPOINT}/Delete/{id}");
                    if (response.IsSuccessStatusCode)
                    {
                        return NoContent();
                    }
                    else
                    {
                        return StatusCode((int)response.StatusCode);
                    }
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"An error occurred: {ex.Message}");
            }
        }
    }
}

BadmintonReservationWebApp/Controllers/DateTypeController.cs
using System.Text;
using BadmintonReservationBusiness;
using BadmintonReservationData;
using BadmintonReservationData.DTOs;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BadmintonReservationWebApp.Controllers;

public class DateTypeController : Controller
{
    private readonly string API_URL_ENDPOINT = "https://localhost:7257/api/DateType";

    public DateTypeController()
    {
    }

    public async Task<IActionResult> Index()
    {
        return View();
    }
    [HttpGet]
    public async Task<List<DateType>> GetAll()
    {
        try
        {
            var result = new List<DateType>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(API_URL_ENDPOINT + "/GetAll"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<List<DateType>>(content);
                    }
                }
            }

            return result;
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }
}

BadmintonReservationWebApp/Controllers/FrameController.cs
using System.Net;
using System.Text;
using BadmintonReservationBusiness;
using BadmintonReservationData;
using BadmintonReservationData.DTO;
using BadmintonReservationData.DTOs;
using BadmintonReservationData.Utils;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BadmintonReservationWebApp.Controllers;

public class FrameController : Controller
{
    private readonly string API_URL_ENDPOINT = "https://localhost:7257/api/Frame";

    public FrameController()
    {
    }

    public async Task<IActionResult> Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Add()
    {
        return PartialView("Add", new CreateFrameRequestDTO
        {
            TimeFrom = 600,
            TimeTo = 700
        });
    }

    [HttpGet]
    public async Task<IActionResult> GetAll(
        int pageIndex = 1,
        int pageSize = 2,
        string? searchText = "",
        double price = 0,
        int status = 0,
        int timeFrom = 0,
        int timeTo = 0)
    {
        try
        {
            var result = new PageableResponseDTO<Frame>();
            using (var httpClient = new HttpClient())
            {
                var queryParams = new List<string>();

                queryParams.Add($"pageIndex={Uri.EscapeDataString(pageIndex.ToString())}");
                queryParams.Add($"pageSize={Uri.EscapeDataString(pageSize.ToString())}");

                if (!string.IsNullOrEmpty(searchText))
                    queryParams.Add($"searchText={Uri.EscapeDataString(searchText)}");
                else
                    queryParams.Add($"searchText={Uri.EscapeDataString("")}");


                if (price != 0)
                    queryParams.Add($"price={price}");
                if (status != 0)
                    queryParams.Add($"status={status}");
                if (timeFrom != 0)
                    queryParams.Add($"timeFrom={timeFrom}");
                if (timeTo != 0)
                    queryParams.Add($"timeTo={timeTo}");

                var queryString = string.Join("&", queryParams);

                var requestUrl = $"{API_URL_ENDPOINT}/GetAll";
                if (!string.IsNullOrEmpty(queryString))
                    requestUrl = $"{requestUrl}?{queryString}";

                using (var response = await httpClient.GetAsync(requestUrl))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<PageableResponseDTO<Frame>>(content);
                        return Ok(result);
                    }
                    else
                    {
                        var errorMessage = $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}";
                        return StatusCode((int)response.StatusCode, errorMessage);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] CreateFrameRequestDTO createFrameRequestDto)
    {
        try
        {
            using (var httpClient = new HttpClient())
            {
                var json = JsonConvert.SerializeObject(createFrameRequestDto);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync(API_URL_ENDPOINT + "/Create", content))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();
                        var createdFrame = JsonConvert.DeserializeObject<Frame>(responseContent);
                        return Ok(createdFrame);
                    }

                    if (response.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var errorMessage = JsonConvert.DeserializeObject<BusinessResult>(await response.Content.ReadAsStringAsync()).Message;
                        return BadRequest(errorMessage);
                    }
                    else
                    {
                        var errorMessage = $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}";
                        return StatusCode((int)response.StatusCode, errorMessage);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        try
        {
            UpdateFrameRequestDTO result = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{API_URL_ENDPOINT}/GetById/{id}"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        var frameResponse = JsonConvert.DeserializeObject<FrameResponseDTO>(content);
                        result = new UpdateFrameRequestDTO()
                        {
                            Id = frameResponse.Id,
                            Label = frameResponse.Label,
                            Note = frameResponse.Note,
                            TimeFrom = TimeConverter.ConvertToTimeSpan(frameResponse.TimeFrom),
                            TimeTo = TimeConverter.ConvertToTimeSpan(frameResponse.TimeTo),
                            OldTimeFrom = frameResponse.TimeFrom,
                            OldTimeTo = frameResponse.TimeTo,
                            OldCourtId = frameResponse.CourtId,
                            Price = frameResponse.Price,
                            CourtId = frameResponse.CourtId,
                            Status = frameResponse.Status
                        };
                    }
                }
            }

            return PartialView("edit", result);
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    [HttpPut]
    public async Task<IActionResult> Update([FromBody] UpdateFrameRequestDTO updateFrameRequestDto)
    {
        try
        {
            using (var httpClient = new HttpClient())
            {
                var json = JsonConvert.SerializeObject(updateFrameRequestDto);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync($"{API_URL_ENDPOINT}/Update", content))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();
                        var updatedFrame = JsonConvert.DeserializeObject<Frame>(responseContent);
                        return Ok(updatedFrame);
                    }

                    if (response.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var errorMessage = JsonConvert.DeserializeObject<BusinessResult>(await response.Content.ReadAsStringAsync()).Message;
                        return BadRequest(errorMessage);
                    }
                    else
                    {
                        var errorMessage = $"Request failed with status code: {response.StatusCode} and reason: {response.ReasonPhrase}";
                        return StatusCode((int)response.StatusCode, errorMessage);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"Internal server error: {ex.Message}");
        }
    }

    [HttpDelete]
    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            using (var httpClient = new HttpClient())
            {
                HttpResponseMessage response = await httpClient.DeleteAsync($"{API_URL_ENDPOINT}/Delete/{id}");
                if (response.IsSuccessStatusCode)
                {
                    return NoContent();
                }
                else
                {
                    return StatusCode((int)response.StatusCode);
                }
            }
        }
        catch (Exception ex)
        {
            return StatusCode(500, $"An error occurred: {ex.Message}");
        }
    }

    [HttpGet]
    public async Task<IActionResult> Report(int id)
    {
        try
        {
            Frame result = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{API_URL_ENDPOINT}/GetByIdIncludeCourt/{id}"))
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        result = JsonConvert.DeserializeObject<Frame>(content);
                    }
                }
            }

            return View("report", result);
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }
}

BadmintonReservationWebApp/Views/CustomFrame/Add.cshtml
@model BadmintonReservationData.DTOs.CreateCustomFrameRequestDTO

<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Specific Date</label>
        @Html.EditorFor(model => model.SpecificDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
        @Html.ValidationMessageFor(model => model.SpecificDate, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Price</label>
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="1">Status</label>
        @Html.DropDownListFor(model => model.Status, new SelectList(new[]
        {
            new { Value = 1, Text = "Active" },
            new { Value = 2, Text = "Inactive" },
        }, "Value", "Text"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Frame</label>
        <select id="CourtId" class="form-control"></select>
        @Html.ValidationMessageFor(model => model.FrameId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Date In Week</label>
        <select id="DateInWeek" class="form-control"></select>
        @Html.ValidationMessageFor(model => model.FrameId, "", new { @class = "text-danger" })
    </div>
</div>
<script>
    $(document).ready(function() {
        getAllFrame();
        getAllData();
    });
    function getAllFrame() {
        $.ajax({
            url: '@Url.Action("GetAll", "Frame")',
                type: "GET",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    // Clear previous options
                    $('#CourtId').empty();
                    // Add each court as an option to the dropdown list

                    $.each(result, function(key, item) {

                        var text = extractHourAndMinute(item.timeFrom) + "-" + extractHourAndMinute(item.timeTo) + "-" 
                        + item.court.name;
                       

                        $('#CourtId').append($('<option>', {
                            value: item.id,
                            text: text,
                        }));
                    });
                },
                error: function (xhr, error) {
                    alert(xhr.statusText);
                    alert(`Something went wrong!`);
                }
        });
    }

    function getAllData() {
        $.ajax({
            url: '@Url.Action("GetAll", "DateType")',
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                // Clear previous options
                $('#DateInWeek').empty();
                // Add each court as an option to the dropdown list
                $.each(result, function (key, item) {
                    $('#DateInWeek').append($('<option>', {
                        value: item.id,
                        text: item.name
                    }));
                });
            },
            error: function (xhr, error) {
                alert(xhr.statusText);
                alert(`Something went wrong!`);
            }
        });
    }

    function extractHourAndMinute(datetimeStr) {
        let date = new Date(datetimeStr);
        let hours = date.getHours().toString().padStart(2, '0');
        let minutes = date.getMinutes().toString().padStart(2, '0');
        return `${hours}:${minutes}`;
    }


</script>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

BadmintonReservationWebApp/Views/CustomFrame/Edit.cshtml
@model BadmintonReservationData.DTOs.UpdateCustomFrameRequestDTO

<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Specific Date</label>
            @Html.LabelFor(model => model.SpecificDate, new { @class = "control-label" })
            @Html.TextBoxFor(model => model.SpecificDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
            @Html.ValidationMessageFor(model => model.SpecificDate, "", new { @class = "text-danger" })

    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Price</label>
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="1">Status</label>
        @Html.DropDownListFor(model => model.Status, new SelectList(new[]
                 {
        new { Value = 1, Text = "Active" },
        new { Value = 2, Text = "Inactive" },
        }, "Value", "Text"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Frame</label>
        <select id="CourtId" class="form-control"></select>
        @Html.ValidationMessageFor(model => model.FrameId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group row">
    <div class="col-md-6">
        <label for="1">Date In Week</label>
        <select id="DateInWeek" class="form-control"></select>
        @Html.ValidationMessageFor(model => model.FrameId, "", new { @class = "text-danger" })
    </div>
</div>
<script>
    $(document).ready(function () {
        getAllFrame(@Model.FrameId);
        getAllData(@Model.DateType);
    });

    function getAllFrame(frameId) {
        $.ajax({
            url: '@Url.Action("GetAll", "Frame")',
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                // Clear previous options
                $('#CourtId').empty();
                // Add each court as an option to the dropdown list

                $.each(result, function (key, item) {

                    var text = extractHourAndMinute(item.timeFrom) + "-" + extractHourAndMinute(item.timeTo) + "-"
                        + item.court.name;


                    $('#CourtId').append($('<option>', {
                        value: item.id,
                        text: text,
                        selected: item.id === frameId
                    }));
                });
            },
            error: function (xhr, error) {
                alert(xhr.statusText);
                alert(`Something went wrong!`);
            }
        });
    }

    function getAllData(dateType) {
        $.ajax({
            url: '@Url.Action("GetAll", "DateType")',
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                // Clear previous options
                $('#DateInWeek').empty();
                // Add each court as an option to the dropdown list
                $.each(result, function (key, item) {
                    $('#DateInWeek').append($('<option>', {
                        value: item.id,
                        text: item.name,
                        selected: item.id === dateType
                    }));
                });
            },
            error: function (xhr, error) {
                alert(xhr.statusText);
                alert(`Something went wrong!`);
            }
        });
    }

    function extractHourAndMinute(datetimeStr) {
        let date = new Date(datetimeStr);
        let hours = date.getHours().toString().padStart(2, '0');
        let minutes = date.getMinutes().toString().padStart(2, '0');
        return `${hours}:${minutes}`;
    }

</script>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}